import pandas as pd
from engine import process
from ml_engine import predict
from alerts import send_alert

df = pd.read_csv("data.csv")

df = process(df)
df = predict(df)

df.to_csv("data.csv", index=False)

for _, row in df.iterrows():
    if row["ml_score"] > 80:
        send_alert(f"""🚨 HIGH VALUE ALERT
Item: {row['item_name']}
Desc: {row['description']}
SKU: {row['sku']}
Store: {row['last_store_location']}
Score: {row['ml_score']}
Price: {row['price']}""")

print("Updated with store location")
