import pandas as pd
from engine import process
from ml_engine import predict
from alerts import send_alert

# Load data
df = pd.read_csv("data.csv")

# Run processing + ML
df = process(df)
df = predict(df)

# Save updated data
df.to_csv("data.csv", index=False)

# SEND ALERTS
for _, row in df.iterrows():

    if row["ml_score"] > 80:

        message = f"""🚨 HOME DEPOT CLEARANCE ALERT

📦 Item: {row['item_name']}
📝 Description: {row['description']}
🏬 Store: {row['last_store_location']}
🏷 SKU: {row['sku']}
💰 Price: ${row['price']}
📉 Discount: {row['drop_pct']}%
📊 Score: {round(row['ml_score'], 2)}

⚡ HIGH VALUE OPPORTUNITY
"""

        send_alert(message)

print("System updated with full alerts")
